### ISSUE TITLE
Crashes upon submitting an expense recording when fields are not full

### ISSUE THREAD

**Issue by oakley8sam** [oakley8sam/ThriftEZ#10]
Hitting the record button without a value in the amount field causes crash

**Comment by anihopkins** [comment]
This can be fixed with the same quick-fix as the new category bug, definitely.

**Comment by anihopkins** [comment]
Also, what happens if other fields are empty?

**Comment by oakley8sam** [comment]
Fixed on 11/22: Populated fields with default values, and shut off the "record expense" button when the category slider has no categories in it.
