### ISSUE TITLE
No way to record repayment

### ISSUE THREAD

**Issue by anihopkins** [oakley8sam/ThriftEZ#2]
Right now there is no way to record deposits. So if someone, for instance, pays out a large sum for utilities and is then payed back by several housemates, there is no way to reflect that.

**Comment by oakley8sam** [comment]
Added ability to record repayments. Follow up: should a repayment that brings current above max balance force max balance to rise? Or should it show the larger number as a special surplus?

**Comment by anihopkins** [comment]
My thinking, and the place that the app is at right now, is showing the large number as a surplus, given that there are not many monthly reimbursements.
