### ISSUE TITLE
App Crashes When Creating Unnamed Category

### ISSUE THREAD

**Issue by anihopkins** [oakley8sam/ThriftEZ#5]
The app crashes when no category name is entered and the user tries to create a new category.

**Comment by oakley8sam** [comment]
doesnt actually crash, just gives blank name

**Comment by anihopkins** [comment]
Ah. Then this is maybe not a bug. I'll move this to "enhancement" so it's clear that this needs to be changed but that it's not strictly a bug.

**Comment by oakley8sam** [comment]
Fixed on 11/22: Gave category name a default value.
