### ISSUE TITLE
Duplicate Category Name Conflicts

### ISSUE THREAD

**Issue by oakley8sam** [oakley8sam/ThriftEZ#9]
If you have two or more categories with the same name and try to edit one, it will change both, but delete only deletes one.

**Comment by anihopkins** [comment]
Possible fix: do something like the Windows filesystem does and force duplicates to be "Category", "Category(1)", "Category(2)", etc. Or, just don't allow creation of a category if a category of that name exists. That might be easier and make more sense.

**Comment by oakley8sam** [comment]
Fixed 11/24: Implemented windows filed viewer type duplication handling, as suggested. (Can now delete and edit without worrying about changing the incorrect category)
